<?php

namespace Tests\Feature;

use App\Livewire\NotificationBell;
use App\Models\Form;
use App\Models\User;
use App\Notifications\DocumentImportedNotification;
use App\Notifications\FormGeneratedNotification;
use App\Notifications\FormSubmittedNotification;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Notification;
use Livewire\Livewire;
use Tests\TestCase;

class NotificationCenterTest extends TestCase
{
    use RefreshDatabase;

    public function test_form_submission_dispatches_notification_to_owner()
    {
        Notification::fake();

        $owner = User::factory()->create();
        $form = Form::create([
            'user_id' => $owner->id,
            'title'   => 'Customer Feedback',
            'schema'  => [
                'sections' => [
                    [
                        'fields' => [
                            ['key' => 'feedback', 'type' => 'text', 'label' => 'Feedback', 'required' => false]
                        ]
                    ]
                ]
            ],
            'status'  => 'published',
            'version' => 1,
        ]);

        Livewire::test(\App\Livewire\Forms\PublicForm::class, ['slug' => $form->slug])
            ->set('answers.feedback', 'Great service!')
            ->call('submit');

        Notification::assertSentTo($owner, FormSubmittedNotification::class);
    }

    public function test_notification_bell_displays_unread_count_and_list()
    {
        $user = User::factory()->create();
        $form = Form::create([
            'user_id' => $user->id,
            'title'   => 'Event RSVP',
            'schema'  => ['sections' => []],
            'status'  => 'published',
            'version' => 1,
        ]);

        $user->notify(new FormSubmittedNotification($form, ['name' => 'John Doe']));
        $user->notify(new FormGeneratedNotification($form, 'generated'));

        $this->assertEquals(2, $user->unreadNotifications()->count());

        Livewire::actingAs($user)
            ->test(NotificationBell::class)
            ->call('toggleDropdown')
            ->assertSee('2 new')
            ->assertSee("New response received on 'Event RSVP'")
            ->assertSee("'Event RSVP' was successfully generated by Gemini AI.");
    }

    public function test_user_can_mark_notifications_as_read()
    {
        $user = User::factory()->create();
        $form = Form::create([
            'user_id' => $user->id,
            'title'   => 'Job Application',
            'schema'  => ['sections' => []],
            'status'  => 'published',
            'version' => 1,
        ]);

        $user->notify(new DocumentImportedNotification($form, 'resume.docx'));

        $notification = $user->unreadNotifications->first();
        $this->assertNotNull($notification);

        Livewire::actingAs($user)
            ->test(NotificationBell::class)
            ->call('markAsRead', $notification->id);

        $this->assertEquals(0, $user->unreadNotifications()->count());
    }

    public function test_user_can_mark_all_notifications_as_read()
    {
        $user = User::factory()->create();
        $form = Form::create([
            'user_id' => $user->id,
            'title'   => 'Survey',
            'schema'  => ['sections' => []],
            'status'  => 'published',
            'version' => 1,
        ]);

        $user->notify(new FormSubmittedNotification($form, []));
        $user->notify(new FormGeneratedNotification($form, 'refined'));

        $this->assertEquals(2, $user->unreadNotifications()->count());

        Livewire::actingAs($user)
            ->test(NotificationBell::class)
            ->call('markAllAsRead');

        $this->assertEquals(0, $user->unreadNotifications()->count());
    }
}
